stages:
  - deploy

variables:
  GCLOUD_PROJECT_ID: myika-anastasia

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCLOUD_ACC_KEY
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCLOUD_PROJECT_ID/chartmaster-$CI_COMMIT_SHORT_SHA
    - gcloud beta run deploy chartmaster --image gcr.io/$GCLOUD_PROJECT_ID/chartmaster-$CI_COMMIT_SHORT_SHA --port 8000 --platform managed --min-instances 0 --max-instances 5 --allow-unauthenticated --region asia-southeast1 --memory 128Mi --cpu 1 --concurrency 5 --timeout 1000 --vpc-connector redis-streams
